// Code generated by trpc-go/trpc-cmdline v1.0.8. DO NOT EDIT.
// source: proto/helloworld.proto

package pb

import (
	"context"
	"errors"
	"fmt"
	reflect "reflect"

	"trpc.group/trpc-go/trpc-codec/grpc"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	"trpc.group/trpc-go/trpc-go/filter"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// GreeterService defines service.
type GreeterService interface {
	Hello(ctx context.Context, req *HelloRequest) (*HelloReply, error)
}

func GreeterService_Hello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GreeterService).Hello(ctx, reqbody.(*HelloRequest))
	}

	// Try to get req from ctx.
	grpcData, grpcEnabled := ctx.Value(grpc.ContextKeyHeader).(*grpc.Header)
	if grpcEnabled {
		req = grpcData.Req.(*HelloRequest)
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	// Set rsp to ctx, and set rsp empty.
	if grpcEnabled {
		grpcData.Rsp = rsp
		rsp = &HelloReply{}
	}
	return rsp, nil
}

// GreeterServer_ServiceDesc descriptor for server.RegisterService.
var GreeterServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.helloworld.Greeter",
	HandlerType: ((*GreeterService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.helloworld.Greeter/Hello",
			Func: GreeterService_Hello_Handler,
		},
	},
}

// RegisterGreeterService registers service.
func RegisterGreeterService(s server.Service, svr GreeterService) {
	if err := s.Register(&GreeterServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Greeter register error:%v", err))
	}
	// register service to grpc
	if err := grpc.Register(GreeterServer_ServiceDesc.ServiceName,
		"proto/helloworld.proto",
		[]grpc.RegisterMethodsInfo{
			{
				Method: server.Method{
					Name: "Hello",
					Func: GreeterService_Hello_Handler,
				},
				ReqType: reflect.TypeOf(HelloRequest{}),
				RspType: reflect.TypeOf(HelloReply{}),
			},
		}); err != nil {
		panic(fmt.Sprintf("grpc register Greeter error:%v", err))
	}
	if err := grpc.RegisterStream(GreeterServer_ServiceDesc.ServiceName,
		"proto/helloworld.proto",
		GreeterServer_ServiceDesc.Streams,
		svr, (*GreeterService)(nil)); err != nil {
		panic(fmt.Sprintf("grpc register Greeter streams error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedGreeter struct{}

func (s *UnimplementedGreeter) Hello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, errors.New("rpc Hello of service Greeter is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// GreeterClientProxy defines service client proxy
type GreeterClientProxy interface {
	Hello(ctx context.Context, req *HelloRequest, opts ...client.Option) (rsp *HelloReply, err error)
}

type GreeterClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewGreeterClientProxy = func(opts ...client.Option) GreeterClientProxy {
	return &GreeterClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *GreeterClientProxyImpl) Hello(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloReply, error) {
	// set req to ctx
	h := ctx.Value(grpc.ContextKeyHeader)
	var header *grpc.Header
	if h == nil {
		header = &grpc.Header{}
		ctx = context.WithValue(ctx, grpc.ContextKeyHeader, header)
	} else {
		var ok bool
		header, ok = h.(*grpc.Header)
		if !ok {
			return nil, errors.New(fmt.Sprintf("grpc header in context cannot be transferred to grpc.Header"))
		}
	}
	header.Req = req
	header.Rsp = &HelloReply{}
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.helloworld.Greeter/Hello")
	msg.WithCalleeServiceName(GreeterServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Greeter")
	msg.WithCalleeMethod("Hello")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloReply{}
	callopts = append(callopts, client.WithProtocol("grpc"))
	callopts = append(callopts, client.WithFilter(func(ctx context.Context, req1, rsp1 interface{}, next filter.ClientHandleFunc) error {
		err := next(ctx, req1, rsp1)
		header := ctx.Value(grpc.ContextKeyHeader).(*grpc.Header)
		*rsp = *header.Rsp.(*HelloReply)
		return err
	}))
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
